export const options = [
  {
    id: "environmentData",
    title: "Obstacle",
    color: "#fef08a",
    spawnPoint: false,
    collisions: true,
    consumable: false,
    // total: 'all',
    score: 0,
    destructable: false,
    callback: (e) => null,
  },
  {
    id: "consumableData",
    title: "Health Potion",
    color: "#4ade80",
    spawnPoint: false,
    collisions: true,
    consumable: true,
    total: 3,
    score: 0,
    destructable: false,
    callback: (e) => console.log(e),
  },
  {
    id: "trapData",
    title: "Spike Trap",
    color: "#fecdd3",
    spawnPoint: false,
    collisions: true,
    consumable: true,
    total: 5,
    score: 0,
    destructable: false,
    callback: (e) => console.log(e),
  },
  {
    id: "spawnData",
    title: "Player Spawn",
    color: "#bfdbfe",
    spawnPoint: true,
    collisions: false,
    consumable: false,
    total: 1,
    score: 0,
    destructable: false,
    callback: (e) => console.log(e),
  },
  {
    id: "enemySpawnData",
    title: "Enemy Spawn",
    color: "#d8b4fe",
    spawnPoint: true,
    collisions: false,
    consumable: false,
    total: 1,
    score: 0,
    destructable: false,
    callback: (e) => console.log(e),
  },
  {
    id: "goalData",
    title: "Coins",
    color: "#94a3b8",
    spawnPoint: false,
    collisions: true,
    consumable: true,
    score: 1,
    // total: 1,
    destructable: false,
    callback: (e) => console.log(e),
  },
];
